# Generated by Django 5.2.7 on 2025-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('order_item', models.CharField(max_length=200)),
                ('extra_food', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('date_time', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
